### PR TITLE
Fixed nil pointer exception when cancelling a context with chromedp.Cancel()

### LINKED ISSUE #1294: Nil pointer exception when cancelling a context with chromedp.Cancel()
#### What versions are you running?

```console
$ go list -m github.com/chromedp/chromedp
github.com/chromedp/chromedp v0.9.1
$ google-chrome --version
Version 112.0.5615.50 (Offizieller Build) (64-Bit)
$ go version
go version go1.20.1 windows/amd64
```

#### What did you do? Include clear steps.

```go
opts := append(
	chromedp.DefaultExecAllocatorOptions[:],
	chromedp.Flag("ignore-certificate-errors", true),
)

if debug {
	opts = append(opts, chromedp.Flag("headless", false))
}

globalContext, _ = chromedp.NewExecAllocator(context.Background(), opts...)

if remoteRendering {
	globalContext, _ = chromedp.NewRemoteAllocator(
		globalContext,
		config.Get().RemoteRenderingURL,
	)
}

...

ctx, _ = chromedp.NewContext(
		globalContext,
		chromedp.WithDebugf(func(s string, i ...interface{}) {}),
		chromedp.WithLogf(func(s string, i ...interface{}) {}),
		chromedp.WithErrorf(func(s string, i ...interface{}) {}),
	) // Disable logging

err = chromedp.Run(ctx, ...)
...

err := chromedp.Cancel(globalContext)
if err != nil {
...
}
```

#### What did you expect to see?
The context should have been canceled or an error should have been returned.

#### What did you see instead?

A nil pointer exception:
```
runtime error: invalid memory address or nil pointer dereference
.../go/pkg/mod/github.com/chromedp/chromedp@v0.9.1/chromedp.go:257
```

I had the context printed out, here is the result before c.cancel() is called in chromedp.go:257
```
&{Allocator:0xc0004266c0 Browser:<nil> Target:<nil> targetID: createBrowserContextParams:<nil> browserContextOwner:false BrowserContextID: browserListeners:[] targetListeners:[] browserOpts:[] cancel:<nil> first:false closedTarget:{noCopy:{} state:{_:{} _:{} v:0} sema:0} allocated:<nil> cancelErr:<nil>}
```

### PR DESCRIPTION
**Pull request by Valentin-Kaiser**
Fixes #1294

### CODE REVIEW

File: chromedp.go [hunk 1]
```diff
@@ -244,7 +244,7 @@ func FromContext(ctx context.Context) *Context {
 // underlying errors happening during cancellation.
 func Cancel(ctx context.Context) error {
 	c := FromContext(ctx)
-	if c == nil {
+	if c == nil || c.cancel == nil {
```
Comment (ZekeLu) [inline chromedp.go:247]: I think we only need to add a check before `c.cancel()` on line 257.

```diff
    } else {
+       // c.cancel is nil when Cancel is wrongly called with a context returned
+       // from chromedp.NewRemoteAllocator or chromedp.NewRemoteAllocator.
+       if c.cancel == nil {
+           return ErrInvalidContext
+       }
        c.cancel()
        c.closedTarget.Wait()
    }
```

**Review by ZekeLu — CHANGES_REQUESTED** [review]
Issue #1294 is a user error, we can try our best to let the user know what's wrong. But we should not complicate the code solely for this purpose. So I think we just need to add a check before `c.cancel()`.

File: chromedp.go (hunk 1 above)
Comment (Valentin-Kaiser) [reply chromedp.go:247]: But `c.cancel()` is called again in line 275, so the error could occur again there.

Furthermore, this error no longer occurs if cancel is passed to the context in chromedp.NewRemoteAllocator or chromedp.NewExecAllocator.

And the correct comment would be:
```
// c.cancel is nil when Cancel is wrongly called with a context returned 
// from chromedp.NewRemoteAllocator or chromedp.NewExecAllocator
```

Comment (ZekeLu) [reply chromedp.go:249]: You are right, `c.cancel` is always called no matter whether `graceful` is true or false. Then we should move this check to line 247 as what you have done.

Good catch for the comment message. Lets put `chromedp.NewExecAllocator` first.

```
// c.cancel is nil when Cancel is wrongly called with a context returned 
// from chromedp.NewExecAllocator or chromedp.NewRemoteAllocator
```

Comment (ZekeLu) [reply chromedp.go:249]: > Furthermore, this error no longer occurs if cancel is passed to the context in chromedp.NewRemoteAllocator or chromedp.NewExecAllocator.

It just hides the issue. If we do this, it will change the behavior of the `Cancel` method. If you think that we should change the behavior, please document the new behavior.

Comment (Valentin-Kaiser) [reply chromedp.go:249]: I think you are right, I have reverted the changes.

File: chromedp.go [hunk 2]
```diff
@@ -244,7 +244,9 @@ func FromContext(ctx context.Context) *Context {
 // underlying errors happening during cancellation.
 func Cancel(ctx context.Context) error {
 	c := FromContext(ctx)
-	if c == nil {
+	// c.cancel is nil when Cancel is wrongly called with a context returned
+	// by chromedp.NewExecAllocator or chromedp.NewRemoteAllocator.
+	if c == nil || c.cancel == nil {
```
Comment (ZekeLu) [inline chromedp.go:249]: Now lets add a test to cover it. Add it after line 263: https://github.com/chromedp/chromedp/blob/97a00b98306467ee7efe556f09fbc9cac0e7c94c/chromedp_test.go#L260-L263

```go
	if err := Cancel(allocCtx); err != ErrInvalidContext {
		t.Fatalf("want error %q, got %q", ErrInvalidContext, err)
	}
```

**Review by ZekeLu — CHANGES_REQUESTED** [review]

File: chromedp_test.go [hunk 3]
```diff
@@ -261,6 +261,12 @@ func TestCancelError(t *testing.T) {
 		t.Fatalf("expected a nil error, got %v", err)
 	}
 
+	allocCtx, allocCancel := NewExecAllocator(context.Background(), allocOpts...)
+	defer allocCancel()
```
Comment (ZekeLu) [inline chromedp_test.go:265]: I think we don't need a new `allocCtx`. Just use the one that already exists.

**Review by ZekeLu — CHANGES_REQUESTED** [review]

File: chromedp_test.go (hunk 3 above)
Comment (Valentin-Kaiser) [reply chromedp_test.go]: You're right, I didn't realise it was already defined.

**Review by ZekeLu — APPROVED** [review]
LGTM. Thank you!
